name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5

    - name: Verify dependencies
      run: make audit/verify

    - name: Run gofmt
      run: make audit/format

    - name: Build
      run: make build

    - name: Run go vet
      run: make audit/vet

    - name: Run staticcheck
      run: make audit/staticcheck

    - name: Run vulncheck
      run: make audit/vulncheck

    - name: Run golint
      run: make audit/lint

    - name: Run tests
      run:  make audit/race
